import streamlit as st
import pandas as pd
import time
import json
import os
from datetime import datetime

# ==========================================
# 1. CONFIGURATION
# ==========================================
st.set_page_config(page_title="Server Command Dashboard v2.4", layout="wide", page_icon="🛡️")

# [LUMA MEMORY] Hard Sell Logic
HARD_SELL_PERCENT = 0.02 # 2% Hard Sell Limit

def calculate_hard_sell(price):
    if price is None or price == 0: return 0.0
    return float(price) * (1 - HARD_SELL_PERCENT)

# ==========================================
# 2. REAL DATA FETCHER
# ==========================================
# CHANGE: Point to the 'data' directory used by main.py on Railway
DATA_FILE = "data/dashboard_state.json" 
if not os.path.exists(DATA_FILE):
    # Fallback: check current directory if running locally without the folder
    DATA_FILE = "dashboard_state.json"

def load_data():
    """Reads the JSON file generated by main.py"""
    if not os.path.exists(DATA_FILE):
        return None
    try:
        with open(DATA_FILE, "r") as f:
            return json.load(f)
    except Exception:
        return None

def get_metrics(data):
    if not data:
        return {
            'Equity': 0.00, 'Cash': 0.00, 'PnL Season': 0.0, 'ROE': 0.0,
            'Market': "OFFLINE", 'Scan Speed': "0ms"
        }
    return {
        'Equity': data.get('equity', 0.0),
        'Cash': data.get('cash', 0.0),
        'PnL Season': data.get('pnl', 0.0),
        'ROE': data.get('account_roe', 0.0),
        'Market': data.get('session', "Unknown"),
        'Scan Speed': "150ms"
    }

def get_scanner_data(data):
    if not data or 'scan_results' not in data:
        return pd.DataFrame()
        
    raw = data['scan_results']
    if not raw:
        return pd.DataFrame()

    df = pd.DataFrame(raw)
    
    # Map Backend Keys to Frontend Columns
    df['Symbol'] = df['coin']
    df['Type'] = "PERP"
    df['Quality'] = df['quality'].apply(lambda x: "✅ Real Frenzy" if "BUY" in str(x) else ("❌ Whale Wick" if "SELL" in str(x) else "Waiting..."))
    df['Price'] = df['price']
    df['Vol (M)'] = df['vol_m']
    
    # Placeholders for data not yet in backend
    df['Speed (1m)'] = 0.0 
    df['TPS'] = 0.0 
    
    # Apply Hard Sell Logic
    df['Liquidation*'] = df['Price'].apply(calculate_hard_sell)
    
    return df[['Symbol', 'Type', 'Speed (1m)', 'TPS', 'Quality', 'Price', 'Vol (M)', 'Liquidation*']]

def get_live_trades(data):
    if not data or 'positions' not in data:
        return pd.DataFrame()

    raw = data['positions']
    if not raw:
        return pd.DataFrame()
        
    df = pd.DataFrame(raw)
    
    df['Symbol'] = df['coin']
    df['Type'] = "PERP"
    df['Open Price'] = df['entry']
    df['PnL'] = df['pnl']
    
    # Estimate ROE/Liq for display if not provided
    margin = (df['Open Price'] * df['size'].abs()) / 5 # Assuming 5x Lev
    df['ROE'] = (df['PnL'] / margin) * 100 if margin else 0
    df['Liq Price'] = df['Open Price'] * 0.8 
    df['Quality'] = df['PnL'].apply(lambda x: "✅ Winning" if x > 0 else "⚠️ Risk")

    return df[['Symbol', 'Type', 'Open Price', 'Quality', 'Liq Price', 'PnL', 'ROE']]

# ==========================================
# 3. DASHBOARD UI LAYOUT
# ==========================================

data_state = load_data()
metrics = get_metrics(data_state)

# Custom CSS
st.markdown("""
<style>
    div[data-testid="stMetricValue"] { font-size: 1.2rem; }
    div[data-testid="stMarkdownContainer"] p { font-size: 0.9rem; }
</style>
""", unsafe_allow_html=True)

# Header
c1, c2, c3, c4, c5, c6 = st.columns(6)
c1.metric("Equity", f"${metrics['Equity']:,.2f}")
c2.metric("Cash", f"${metrics['Cash']:,.2f}")
c3.metric("PnL Season", f"{metrics['PnL Season']}%", delta=metrics['PnL Season'])
c4.metric("ROE", f"{metrics['ROE']}%", delta=metrics['ROE'])
c5.metric("Market", metrics['Market'])
c6.metric("Scan Speed", metrics['Scan Speed'])

st.divider()

# Scanner Section
st.subheader("📡 Velocity Scanner (Futures)")
st.caption("Live Feed • 1m Burst Speed • Hard Sell Liquidation Projections")

scanner_df = get_scanner_data(data_state)

if not scanner_df.empty:
    st.dataframe(
        scanner_df,
        column_config={
            "Symbol": st.column_config.TextColumn("Symbol", width="medium"),
            "Speed (1m)": st.column_config.ProgressColumn("Speed (1m)", format="%.2f %%", min_value=0, max_value=25),
            "TPS": st.column_config.NumberColumn("TPS", format="%.1f"),
            "Price": st.column_config.NumberColumn("Price", format="$%.5f"),
            "Vol (M)": st.column_config.NumberColumn("Vol (M)", format="%.2f M"),
            "Liquidation*": st.column_config.NumberColumn("Liquidation (Hard Sell)", format="$%.5f"),
        },
        use_container_width=True,
        hide_index=True
    )
else:
    st.info("Scanner Initializing... Waiting for Main Loop Data.")

st.divider()

# Positions Section
st.subheader("⚡ Live Positions")
st.caption("Active Executions • Real-time PnL")

live_df = get_live_trades(data_state)

if not live_df.empty:
    st.dataframe(
        live_df,
        column_config={
            "Open Price": st.column_config.NumberColumn("Entry", format="$%.5f"),
            "Liq Price": st.column_config.NumberColumn("Liq Price", format="$%.5f"),
            "PnL": st.column_config.NumberColumn("PnL ($)", format="$%.2f"),
            "ROE": st.column_config.NumberColumn("ROE (%)", format="%.2f %%"),
        },
        use_container_width=True,
        hide_index=True
    )
else:
    st.write("No active positions.")

# Auto Refresh (2 seconds)
time.sleep(2)
st.rerun()
